#!/bin/bash

if [[ ! -e /var/run/heatinit.pid ]]; then
    source /root/localrc

    echo "Configuring MySQL..."
    mysql_install_db
    /usr/bin/mysqld_safe & 
    /root/create_mysql_admin_user.sh

    echo "Updating rabbitmq password..."
    /etc/init.d/rabbitmq-server start
    rabbitmqctl change_password guest "${RABBITMQ_PASSWORD}"

    echo "Setting up heat database..."
    heat-db-setup deb --yes -r "${DATABASE_ROOT_PASSWORD}" -p "${DATABASE_HEAT_PASSWORD}"

    touch /var/run/heatinit.pid
else
    echo "Now starting MySQL..."
    # /etc/init.d/mysql start
    mysqld_safe & 
    sleep 2

    echo "Now starting RabbitMQ..."
    /etc/init.d/rabbitmq-server start
fi

echo "Now starting heat in the background..."
heat-engine &>> /tmp/heat.log &
heat-api &>> /tmp/heat.log &
heat-api-cfn &>> /tmp/heat.log &
heat-api-cloudwatch &>> /tmp/heat.log 
