#!/bin/bash

if [[ ! -e /var/log/heat/heatinit ]]; then
    source /root/localrc

    echo " * Updating rabbitmq password..."
    rabbitmqctl change_password guest "${RABBITMQ_PASSWORD}"

    echo " * Setting up heat database..."
    bin/heat-db-setup deb -r "${DATABASE_PASSWORD}"

    touch /var/log/heat/heatinit
fi

echo "Now starting heat in the background..."
heat-engine &> /dev/null &
heat-api &> /dev/null &

echo
echo "heat-engine pid: $(pidof -x heat-engine)"
echo "heat-api pid: $(pidof -x heat-api)"
echo "heat logs: /var/log/heat"

echo
echo "To access heat, export HEAT_URL=http://${PUBLIC_IP}:8004/v1/\${OS_TENANT_ID}"
echo "Newer versions of heat client also require: export OS_NO_CLIENT_AUTH=1"
echo
